// <auto-generated />
namespace CoffeStreet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class prd_desc_im_changed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(prd_desc_im_changed));
        
        string IMigrationMetadata.Id
        {
            get { return "202005230551067_prd_desc_im_changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
